constant_fields:
  category: quality
  firstPerformanceYear: 2017
  lastPerformanceYear: null    
  metricType: singlePerformanceRate
  eMeasureId: null
  nqfEMeasureId: null
  nqfId: null
  # TODO(aimee): what should primarySteward be?
  primarySteward: PIMMS
  strata:
    - name: overall
  measureSets: []
sourced_fields:
  measureId: 2
  title: 3
  description: 4
  nationalQualityStrategyDomain: 5
  measureType: 13
  isHighPriority:
    index: 14
    mappings:
      'High Priority': true
      default: false
  isInverse:
    index: 16
    mappings:
      N: false
      Y: true
      default: false
  isRiskAdjusted:
    index: 20
    mappings:
      N: false
      Y: true
      default: false
