constant_fields:
  category: quality
  firstPerformanceYear: 2017
  lastPerformanceYear: null    
  metricType: singlePerformanceRate
  # TODO(aimee): check if we can remove these
  eMeasureId: null
  nqfEMeasureId: null
  nqfId: null
  # TODO(aimee): what should primarySteward be?
  primarySteward: PIMMS
  strata:
    - name: overall
  measureSets: []
sourced_fields:
  # TODO(aimee): measureIds are not currently unique
  measureId: 2
  title: 3
  description: 4
  nationalQualityStrategyDomain: 5
  measureType:
    index: 13
    mappings:
      Process: process
      Outcome: outcome
      'Patient Engagement/Experience ': patientEngagementExperience
      'Patient Engagement/Experience': patientEngagementExperience
      'Efficiency': efficiency
      'Intermediate Outcome': intermediateOutcome
      'Structure': structure
      # TODO(aimee): verify these mappings
      'Patient Reported Outcome': outcome
      'Composite': outcome
      'Cost/Resource Use': efficiency
      'Cost/resource Use': efficiency
      'Clinical Process Effectiveness': process
  isHighPriority:
    index: 14
    mappings:
      'High Priority': true
      default: false
  isInverse:
    index: 16
    mappings:
      N: false
      Y: true
      default: false
  isRiskAdjusted:
    index: 20
    mappings:
      N: false
      Y: true
      default: false
